### ISSUE TITLE
ejs模板中使用<%include('footer')%>，提示错误：Could not find include include file.

### ISSUE THREAD

**Issue by numa001** [gwuhaolin/web-webpack-plugin#10]

**Comment by gwuhaolin** [comment]
请提供 Webpack 配置和项目目录结构

**Comment by numa001** [comment]
我就拿这个https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/use-template-complier测试。
![image](https://user-images.githubusercontent.com/7803318/29861753-e987326c-8d9c-11e7-969b-b06ab3f3baed.png)
template.ejs：
<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="./reset.min.css?_inline">
	<title><%= title %></title>
</head>
<body>
<script src="./google-analyze.js"></script>
<%-include('./footer')%>
</body>
</html>

**Comment by gwuhaolin** [comment]
这是 ejs 使用不当造成的，当你在 ejs 模版里使用了 include 语句时，就必须在 render 的时候带上 filename 属性，如下：
```js
return ejs.render(ejsTemplate, {
  title: pageName,
  filename: './template.ejs'
});
```

来自[ejs 官方文档](http://ejs.co)：
> Includes are relative to the template with the include call. (This requires the 'filename' option.) 

[本项目的demo](https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/use-template-complier)也已经更新，加上了 include 的使用。

**Comment by numa001** [comment]
谢谢！不过 ejs中如打包图片。像这样：`<img src="<%=require('./test.jpg')%>">`？(报错)

**Comment by gwuhaolin** [comment]
> `<img src="<%=require('./test.jpg')%>">` 

这种方式还不支持，这种方式太不 “Webpack” 了，你可以通过在 JS 中 去 `require('./test.jpg')` 实现。
