### ISSUE TITLE
请问支持多模板吗？

### ISSUE THREAD

**Issue by xiongchengqing** [gwuhaolin/web-webpack-plugin#12]
切活动页面通常会有这种需求，每个页面的布局不一样，能为每个页面设置模板吗

**Comment by gwuhaolin** [comment]
能。 
https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/use-template-complier

**Comment by xiongchengqing** [comment]
@gwuhaolin 谢谢！
