### ISSUE TITLE
如何定义html的输出路径呢？

### ISSUE THREAD

**Issue by shufenghua** [gwuhaolin/web-webpack-plugin#15]
现在html模板渲染之后是直接放到output的path路径下面，如果我想把html渲染之后的文件放到不同的文件夹下面，有方法配置吗？

**Comment by shufenghua** [comment]
另外补充一点，当使用AutoWebPlugin的时候，filename配置貌似没有什么作用，输出都是以entry所在文件夹作为文件名的

**Comment by gwuhaolin** [comment]
提供 Webpack 提供的 `output.path` 能控制文件的输出目录。
在 AutoWebPlugin 中，输出的 html 文件名称只能是由文件夹名称指定，filename 将不在有效。
