### ISSUE TITLE
请问对于AutoWebPlugin的output能定制吗？

### ISSUE THREAD

**Issue by zyg-github** [gwuhaolin/web-webpack-plugin#2]
比如:

<img src="http://7xj3hw.com1.z0.glb.clouddn.com/web-webpack-plugin-AutoWebPlugin-issue.png">

**Comment by gwuhaolin** [comment]
目前还不能，我想了一下要实现这个功能改动很大。而且这个功能的必要性好像只在于让输出结果更整齐，不会有实质性的功能提升。在我们的项目实战中目前这样做也不会产生什么副作用

<img width="500" alt="screen shot 2017-06-05 at 5 43 46 pm" src="https://cloud.githubusercontent.com/assets/5773264/26779118/c2daf00a-4a16-11e7-8e1c-b6fbcee0bc2c.png">

**Comment by zyg-github** [comment]
也是
目录结构一般也不在生产环境维护~
