### ISSUE TITLE
多页面时如何配置生成html文件的文件名和路径

### ISSUE THREAD

**Issue by Zohner** [gwuhaolin/web-webpack-plugin#22]
使用AutoWebPlugin配置多页面，通过filename来修改生成后的html文件名无效，另外想单独配置html文件的生成路径，可以办到么
```
filename: (filename) => {
	return 'test_' + filename
},
```

**Comment by gwuhaolin** [comment]
是支持的，可以查看demo
https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/auto-plugin-logic-filename
