### ISSUE TITLE
多页面场景下怎么忽略入口

### ISSUE THREAD

**Issue by Zohner** [gwuhaolin/web-webpack-plugin#24]
在多页面配置下每个页面文件夹下默认是以index.js作为入口模块加载，但一些页面确实是不需要有单独的入口的，比如一个错误页面，本身没有其它逻辑的，只需要注入公共模块就够了，这种情况下是不需要单独入口的，但是如果不加index.js，打包编译时就会报错，如果加一个空的index.js，虽然不报错，但是编译后就会生成那个js文件，虽然只有一行，但是html也会引入进去，怎么解决这个问题呢

**Comment by gwuhaolin** [comment]
忽略`'pageName1','pageName2'`的配置代码如下
```js
new AutoWebPlugin({
  ignorePages:['pageName1','pageName2']
})
```
