### ISSUE TITLE
index.html中如何添加挂载点id=app

### ISSUE THREAD

**Issue by crowphy** [gwuhaolin/web-webpack-plugin#25]
如题，打包出来的index.html中如何设置以添加挂载点<div id=app></div>

**Comment by gwuhaolin** [comment]
可以查看demo
https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/use-template

在 `template.html` 文件中插入挂载点代码：
```html
<!DOCTYPE html>
<html lang="zh-cn">
<body>
<div id="app"></div>
<!--SCRIPT-->
</body>
</html>
```
