### ISSUE TITLE
感觉名字是不是可以跟专一点？

### ISSUE THREAD

**Issue by zyg-github** [gwuhaolin/web-webpack-plugin#3]
弱弱的问名字是不是可以跟专一点？好容易搞混

**Comment by gwuhaolin** [comment]
[web-webpack-plugin](https://github.com/gwuhaolin/web-webpack-plugin) 插件的意图是补足webpack针对web项目的能力，其中最重要的html的生成和把webpack生成的资源注入到html里去。所以就给他叫 web-webpack-plugin 了

**Comment by zyg-github** [comment]
是我纠结了点~  
可以忽略这个问题~ 嘻嘻~
