### ISSUE TITLE
webpack4.6.0, 版本异常， 无法合并html

### ISSUE THREAD

**Issue by likeDoMine** [gwuhaolin/web-webpack-plugin#30]
(node:7068) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 throw new Error("Chunk.parents: Use ChunkGroup.add/removeParent() instead");
Error: Chunk.parents: Use ChunkGroup.add/removeParent() instead

**Comment by gwuhaolin** [comment]
webpack4请配合最新的web-webpack-plugin4使用
