### ISSUE TITLE
AutoWebPlugin 中没有 commonsChunk 选项？

### ISSUE THREAD

**Issue by KokoTa** [gwuhaolin/web-webpack-plugin#32]
**问题**

在看书进行到多页管理配置时，commonsChunk 提取公用代码无效，源代码似乎没有这个选项

Webpack4 下使用 splitChunks 不知道如何提取公用代码

**Comment by gwuhaolin** [comment]
commonsChunk在webpack4和web-webpack-plugin4中已经废弃。
Webpack4 下使用 splitChunks 如何提取公用代码见demo：
https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/auto-plugin-react-typescript
