### ISSUE TITLE
Cannot read property 'data' of null 打包时报这个错误

### ISSUE THREAD

**Issue by Leafykn** [gwuhaolin/web-webpack-plugin#39]
![WX20190606-161331](https://user-images.githubusercontent.com/26517379/59017449-23d21600-8876-11e9-860e-286766610877.png)

**Comment by musicode** [comment]
+1，不写 `<!--SCRIPT-->` 就会报这个错
@gwuhaolin 能不能修复一下呢

**Comment by gwuhaolin** [comment]
fixed in web-webpack-plugin@4.6.4
