### ISSUE TITLE
<script>是否添加crossorigin属性判断建议

### ISSUE THREAD

**Issue by HexMox** [gwuhaolin/web-webpack-plugin#41]
https://github.com/gwuhaolin/web-webpack-plugin/blob/123736adbc49b2db61f083c6805c6040deeff81c/lib/Resource.js#L99

这里应该结合script标签是否inline，且src属性值是否有效来添加

**Comment by gwuhaolin** [comment]
已经知道自定义自动注入的HTML标签属性，见demo
https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/config-html-attribute
