### ISSUE TITLE
stylePublicPath 参数 如何用呢？ 我想把css文件放到css文件夹里，JS同理

### ISSUE THREAD

**Issue by numa001** [gwuhaolin/web-webpack-plugin#8]

**Comment by gwuhaolin** [comment]
相对路径是支持的，你可以参考这个https://github.com/gwuhaolin/web-webpack-plugin/issues/4
放到CSS文件夹JS文件夹的这[有个demo](https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/relative-path)

`stylePublicPath`用法和`output.publicPath`的完全一样。只不过`output.publicPath`是准对js文件的，`stylePublicPath`是准对css文件的。`stylePublicPath`在`AutoWebPlugin`的属性里配置，
下面这个例子分别把JS、CSS、IMG放到不同的CDN下，代码如下：
```js
const CND = {
  js: `//7.url.cn/edu/${name}/`,
  css: `//8.url.cn/edu/${name}/`,
  img: `//9.url.cn/edu/${name}/`
};
const autoPlugin = new AutoWebPlugin('./src/pages/', {
  // 所有的css文件都放在8.url.cn
  stylePublicPath: CND.css,
});

module.exports = {
  entry: autoPlugin.entry({
    vendor: './src/assets/vendor',
  }),
  output: {
    path: path.resolve(__dirname, `public/cdn/${name}`),
    publicPath: CND.js,
    filename: '[name]_[chunkhash].js',
  },
module: {
    rules: [
      {
        test: /\.css$/,
        // 提取出css
        loaders: ExtractTextPlugin.extract({
          // 通过css加载的文件都放在9.url.cn
          publicPath: CND.img,
          fallback: 'style-loader',
          // 压缩css
          use: ['css-loader?minimize'],
        }),
      },
      {
        test: /\.(gif|png|jpe?g|eot|woff|ttf|svg|pdf)$/,
        loader: 'file-loader',
      },
    ]
  },
}
```

以上。希望能解决你的问题帮到你。用的开心可以告诉你的朋友。

**Comment by numa001** [comment]
谢谢你的热心回复。。可能我的需求比较偏。貌似还是无法满足。
![image](https://user-images.githubusercontent.com/7803318/27939707-334b70c6-62f9-11e7-83d9-6c983f45ec8c.png)

**Comment by gwuhaolin** [comment]
你看看这个两个demo
- [calculate relative paths](https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/relative-path)
- [calculate relative paths(with publicPath)](https://github.com/gwuhaolin/web-webpack-plugin/tree/master/demo/relative-path-public-path)

有没有和你相识的地方，如果没有你可以再把你的需求写详细点，我愿意为你写一个demo

**Comment by numa001** [comment]
谢谢，我仔细琢磨了，AutoWebPlugin   基本上能满足我的需求。
但是有个小BUG: <img src="img/math.png" alt="math">能分离出图片；但是 <a href=""><img src="img/math.png" alt="math"></a> 分离不出图片

此外：我还有个小要求。。
AutoWebPlugin 自动探测html入口 ，现在只能自动探测入口下的一级文件夹，能不能探测二级，三级。。等？

**Comment by gwuhaolin** [comment]
要在HTML里加载本地文件，文件路径前要加`./`用于区分这不是加载webpack里的chunk，代码如下
```html
<img src="./local/path.png">
```

把所有页面都放在同一级是一个很好的习惯，因为这便于管理和维护，目录整齐规范。如果你非要这么干，你可以手动为每个页面写一个`WebPlugin`

**Comment by numa001** [comment]
`<a href=""><img src="./img/math.png" alt="math"></a>`

**Comment by numa001** [comment]
AutoWebPlugin  插入的 <script src="..."></script> 能不能放在HEAD中，当前放在body的最下面。

**Comment by gwuhaolin** [comment]
已经修复，请升级到 1.8.5 版本

**Comment by numa001** [comment]
有个小问题，如何把分离出来的图片放到指定的文件夹里去？

**Comment by gwuhaolin** [comment]
目前只有通过webpack加载的图片可以指定输出目录，直接加载本地的还不支持。

**Comment by numa001** [comment]
...这样html 里的图片一多，生成后都放在dist根目录下。太乱了。。

**Comment by gwuhaolin** [comment]
我支持下加个配置属性

**Comment by numa001** [comment]
我的基于多页面的。  假如 A1.html,A2.html,A3.html, 共用一个A.js ,  B1.html,B2.html,B3.html, 共用一个B.js , 
commonsChunk 该怎么写？ 貌似不行(只能写一个)。。

**Comment by gwuhaolin** [comment]
这个你就不能使用`AutoWebPlugin`提供的`commonsChunk`选项了，因为`AutoWebPlugin`提供的`commonsChunk`选项只能是针对`AutoWebPlugin`找到的所有页面提取公共代码。
如果你想要动态灵活的提取任何几个页面的代码，你需要直接额外的用`CommonsChunkPlugin`去提取。其实`AutoWebPlugin`的提取公共代码的实现就是使用`CommonsChunkPlugin`。

`AutoWebPlugin`会为它找到的每个页面生成一个名叫这个页面目录的chunk。你可以提前这些chunk的公共部分来提取任意页面的公共代码。

**Comment by numa001** [comment]
新增 配置属性 ： 分离出html里的图片到指定目录 功能可以用了吗？

**Comment by numa001** [comment]
分离出html里的图片到指定目录 功能 ， 不好操作的话。  能不能在源代码里面写死？代码在那个地方(我看了源代码好久都找不到。。)

**Comment by gwuhaolin** [comment]
大概在这里
https://github.com/gwuhaolin/web-webpack-plugin/blob/master/lib/Resource.js#L250

我最近有点忙，你要是等不急可以自己尝试着改下提merge。
