### ISSUE TITLE
关于自定义输出目录

### ISSUE THREAD

**Issue by zhw2590582** [gwuhaolin/web-webpack-plugin#9]
这个插件非常棒，以前都是要结合好几个插件才能实现的功能，这个都综合到一起了。
不过对我这种强迫症的人来说，保持好的输出结构和Url是必需的。
再次感谢你的插件。

**Comment by gwuhaolin** [comment]
> 关于自定义输出目录
具体是希望做什么事情？

**Comment by zhw2590582** [comment]
#2 正如他所说的那样，当页面存在多级关系时，可以通过URL展示层级关系

**Comment by gwuhaolin** [comment]
要实现这个会对目前的功能产生很大的改动，去维护构建出来的代码的目录结构意义也不大，应该在意源代码的目录结构。

**Comment by cseve123** [comment]
想通过这个构建文件夹和文件模版，有什么办法动态输出目录了
